<?php
/**
 * @file
 * Code for the DruTACT Resource Import feature.
 */

include_once 'drutact_resource_import.features.inc';

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * Default action links (Import Resources).
 */
function drutact_resource_import_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  switch ($root_path) {
    case 'admin/content/resources':
      // 'Import Resource' action link.
      $item = menu_get_item('import/import_resources_csv');
      $item['title'] = t('Import Resources');
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
      break;
  }
}

/**
 * Implements hook_post_features_rebuild().
 *
 * Default feed permissions (import_resources_csv).
 */
function drutact_resource_import_post_features_rebuild($component) {
  if ($component == 'feeds_tamper') {
    // Default feed permissions (import_resources_csv).
    _drutact_import_default_feed_permissions('import_resources_csv');
  }
}
