<?php
/**
 * @file
 * Install, update and uninstall functions for DruTACT WYSIWYG.
 */

/**
 * Implements hook_install().
 */
function drutact_wysiwyg_install() {
  // Default module permissions (filter).
  _drutact_default_module_permissions(array(
    DRUPAL_ANONYMOUS_RID => array(),
    DRUPAL_AUTHENTICATED_RID => array(),
    DRUTACT_EDITOR_RID => array(),
    DRUTACT_ADMINISTRATOR_RID => array(
      // Filter
      'administer filters',
    ),
  ));
}
