<?php
/**
 * @file
 * Code for the DruTACT Email feature.
 */

include_once 'drutact_email.features.inc';

/**
 * Implements hook_form_alter().
 *
 * Pre-populate mimemail_send_email_action form.
 */
function drutact_email_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  if (isset($form_state['values']['operation']) && $form_state['values']['operation'] == 'action::mimemail_send_email_action') {
    if (isset($form_state['step']) && $form_state['step'] == 'views_bulk_operations_config_form') {
      // Pre-populate mimemail_send_email_action form.
      $form['key']['#value'] = 'drutact_email';
      $form['key']['#access'] = false;
      $form['to']['#value'] = '[user:mail]';
      $form['to']['#access'] = false;
      $form['cc']['#access'] = false;
      $form['bcc']['#access'] = false;
      $form['reply-to']['#access'] = (isset($user->mail)) ? false : true;
      $form['body']['#format'] = (isset($user->mail)) ? 'html' : 'plain_text';
      $form['plaintext']['#access'] = false;
      $form['attachments']['#access'] = false;
      $form['actions']['submit']['#value'] = t('Send');
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add 'Email logo' file component to MIME Mail settings form.
 */
function drutact_email_form_mimemail_admin_settings_alter(&$form, &$form_state, $form_id) {
  // Add 'Email logo' file component to MIME Mail settings form.
  $form['drutact_email_logo'] = array(
    '#title' => t('Path to Email logo file'),
    '#type' => 'textfield',
    '#default_value' => variable_get('drutact_email_logo', ''),
    '#weight' => -10,
  );
  $form['#validate'][] = '_drutact_email_logo_file_validate';
}

/**
 * Custom validation handler for mimemail-admin-settings form.
 *
 * Make sure email logo file exists.
 */
function _drutact_email_logo_file_validate($form, &$form_state) {
  // Make sure email logo file exists.
  $email_logo_uri = 'public://' . $form_state['values']['drutact_email_logo'];
  if (!file_exists(drupal_realpath($email_logo_uri))) {
    form_set_error('drutact_email_logo', t('Logo file does not exist.'));
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Hide Mime Mail settings from user profile form.
 */
function drutact_email_form_user_profile_form_alter(&$form, &$form_state) {
  // Hide Mime Mail settings from user profile form.
  $form['mimemail']['#access'] = FALSE;
}

/**
 * Implements hook_preprocess_mimemail_message().
 *
 * Provide $base_url and $logo_url values to mimemail-message template.
 */
function drutact_email_preprocess_mimemail_message(&$variables) {
  // Provide $base_url value.
  global $base_url;
  $variables['base_url'] = $base_url;

  // Provide $logo_url if file exists.
  $logo_uri = 'public://' . variable_get('drutact_email_logo', '');
  if (file_exists(drupal_realpath($logo_uri))) {
    $variables['logo_url'] = file_create_url($logo_uri);
  }
  else {
    $variables['logo_url'] = $base_url . '/themes/bartik/logo.png';
  }
}
