<?php
/**
 * @file
 * Code for the DruTACT User feature.
 */

include_once 'drutact_user.features.inc';

/**
 * Implements hook_action_info().
 *
 * Email password reset link action.
 */
function drutact_user_action_info() {
  // Email password reset link action.
  $action = array(
    'drutact_user_email_password_reset_link_action' => array(
      'type' => 'user',
      'label' => t('Email password reset link'),
      'configurable' => FALSE,
      'vbo_configurable' => FALSE,
    ),
  );
  return $action;
}

/**
 * Action definition for sending Email password reset link.
 */
function drutact_user_email_password_reset_link_action(&$user, $context) {
  // Send password reset link by email to the user.
  _user_mail_notify('password_reset', $user);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Notify user of new account by default.
 */
function drutact_user_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  // Notify user of new account by default.
  $form['account']['notify']['#default_value'] = TRUE;
}

/**
 * Implements hook_menu_alter().
 *
 * Rename people administration tab from List to Users.
 */
function drutact_user_menu_alter(&$items) {
  // Rename people administration tab from List to Users.
  $items['admin/people/people']['title'] = 'Users';
}
