<?php
/**
 * @file
 * Code for the DruTACT Core feature.
 */

include_once 'drutact_core.features.inc';

/**
 * Implements hook_post_features_rebuild().
 */
function drutact_core_post_features_rebuild($component) {
  if ($component == 'user_role') {
    // Default module permissions (ctools, date, features, rules, tadaa, views).
    _drutact_default_module_permissions(array(
      DRUPAL_ANONYMOUS_RID => array(
        // Date
        'view date repeats',
      ),
      DRUPAL_AUTHENTICATED_RID => array(
        // Date
        'view date repeats',
      ),
      DRUTACT_EDITOR_RID => array(
        // Date
        'view date repeats',
      ),
      DRUTACT_ADMINISTRATOR_RID => array(
        // CTools
        'use ctools import',
        // Date
        'view date repeats',
        // Features
        'administer features',
        'generate features',
        'manage features',
        'rename features',
        // Rules
        'administer rules',
        'bypass rules access',
        'access rules debug',
        // Tadaa
        'access tadaa toolbar',
        'use tadaa',
        // Views
        'administer views',
        'access all views',
      ),
    ));
  }
}
