<?php
/**
 * @file
 * Code for the DruTACT Article Import feature.
 */

include_once 'drutact_article_import.features.inc';

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * Default action links (Import Articles).
 */
function drutact_article_import_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  switch ($root_path) {
    case 'admin/content':
      // 'Import Article' action link.
      $item = menu_get_item('import/import_articles_csv');
      $item['title'] = t('Import Articles');
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
      break;
  }
}

/**
 * Implements hook_post_features_rebuild().
 *
 * Default feed permissions (import_articles_csv).
 */
function drutact_article_import_post_features_rebuild($component) {
  if ($component == 'feeds_tamper') {
    // Default feed permissions (import_articles_csv).
    _drutact_import_default_feed_permissions('import_articles_csv');
  }
}
