<?php
/**
 * @file
 * Code for the DruTACT Media feature.
 */

include_once 'drutact_media.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Custom display of file destination options (add file).
 */
function drutact_media_form_file_entity_add_upload_alter(&$form, &$form_state, $form_id) {
  // Custom display of file destination options (add file).
  if ($form['#step'] == 3) {
    $form['scheme']['#options']['public'] = t('Public files');
    $form['scheme']['#options']['private'] = t('Private files');
    $form['scheme']['#description'] = t('Public files are accessible to everyone, while access to private files must be explicitly granted (i.e. through group access).');
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Custom display of file destination options (edit file).
 */
function drutact_media_form_file_entity_edit_alter(&$form, &$form_state, $form_id) {
  // Custom display of file destination options (edit file).
  $form['destination']['#type'] = 'container';
  $form['destination']['scheme']['#description'] = t('Public files are accessible to everyone, while access to private files must be explicitly granted (i.e. through group access).');
  $form['destination']['#weight'] = -5;
  unset($form['destination']['#group']);
}

/**
 * Implements hook_post_features_rebuild().
 *
 * Revert feature components (file_display).
 */
function drutact_media_post_features_rebuild($component) {
  if ($component == 'file_display') {
    // Revert feature components (file_display).
    features_revert(array('drutact_media' => array('file_display')));
  }
}
