<?php
/**
 * @file
 * Install, update and uninstall functions for DruTACT Media.
 */

/**
 * Implements hook_install().
 */
function drutact_media_install() {
  // Default module permissions (image).
  _drutact_default_module_permissions(array(
    DRUPAL_ANONYMOUS_RID => array(),
    DRUPAL_AUTHENTICATED_RID => array(),
    DRUTACT_EDITOR_RID => array(),
    DRUTACT_ADMINISTRATOR_RID => array(
      // Image
      'administer image styles',
    ),
  ));
}
