<?php
/**
 * @file
 * Code for the DruTACT Administration feature.
 */

include_once 'drutact_admin.features.inc';

/**
 * Implements hook_features_banish_alter().
 */
function drutact_admin_features_banish_alter(&$banished) {
  global $conf;
  $keys = array_keys($conf);
  $banished['variable'] = is_array($banished['variable']) ? $banished['variable'] : array();

  foreach ($keys as $key) {
    // Banish most of the annoying __active_tab variables.
    if (strpos($key, '__active_tab') !== FALSE) {
      $banished['variable'][] = $key;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function drutact_admin_form_taxonomy_form_term_alter(&$form, &$form_state, $form_id) {
  // Enable additional settings vertical tabs on taxonomy term form.
  $form['additional_settings'] = array(
    '#type' => 'vertical_tabs',
    '#weight' => 99,
    '#attached' => array(
      'js' => array(drupal_get_path('module', 'node') . '/content_types.js'),
    ),
  );
  foreach ($form as $delta => $element) {
    if (is_array($element)) {
      if (!empty($element['#type'])) {
        if ($element['#type'] == 'fieldset') {
          $form[$delta]['#group'] = 'additional_settings';
          $form['additional_settings'][$delta] = $form[$delta];
          unset($form[$delta]);
        }
      }
    }
  }
}
