<?php
/**
 * @file
 * Code for the DruTACT Event Import feature.
 */

include_once 'drutact_event_import.features.inc';

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * Default action links (Import Events).
 */
function drutact_event_import_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  switch ($root_path) {
    case 'admin/content/events':
      // 'Import Event' action link.
      $item = menu_get_item('import/import_events_csv');
      $item['title'] = t('Import Events');
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
      break;
  }
}

/**
 * Implements hook_post_features_rebuild().
 *
 * Default feed permissions (import_events_csv).
 */
function drutact_event_import_post_features_rebuild($component) {
  if ($component == 'feeds_tamper') {
    // Default feed permissions (import_events_csv).
    _drutact_import_default_feed_permissions('import_events_csv');
  }
}
