<?php
/**
 * @file
 * Code for the DruTACT Resource feature.
 */

include_once 'drutact_resource.features.inc';

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * Default action links (Add Resource).
 */
function drutact_resource_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  switch ($root_path) {
    case 'admin/content/resources':
      // Default action links (Add Resource).
      $item = menu_get_item('node/add/resource');
      $item['title'] = t('Add Resource');
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
      break;
  }
}

/**
 * Implements hook_post_features_rebuild().
 *
 * Default content permissions (resource).
 */
function drutact_resource_post_features_rebuild($component) {
  if ($component == 'ctools') {
    // Default content permissions (resource).
    _drutact_default_content_type_permissions('resource');
  }
}

/**
 * Implements hook_theme_registry_alter().
 *
 * Add custom templates path.
 */
function drutact_resource_theme_registry_alter(&$registry) {
  // Add custom templates path.
  $path = drupal_get_path('module', 'drutact_resource') . '/templates';
  $templates = drupal_find_theme_templates($registry, '.tpl.php', $path);
  foreach ($templates as $key => $value) {
    $templates[$key]['type'] = 'module';
  }
  $registry += $templates;
}

// Translatables
// Included for use with string extractors like potx.

t('Resources');