<?php
/**
 * @file
 * Code for the DruTACT Event feature.
 */

include_once 'drutact_event.features.inc';

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * Default action links (Add Event).
 */
function drutact_event_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  switch ($root_path) {
    case 'admin/content/events':
      // Default action links (Add Event).
      $item = menu_get_item('node/add/event');
      $item['title'] = t('Add Event');
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
      break;
  }
}

/**
 * Implements hook_post_features_rebuild().
 *
 * Default content type permissions (event).
 */
function drutact_event_post_features_rebuild($component) {
  if ($component == 'ctools') {
    // Default content type permissions (event).
    _drutact_default_content_type_permissions('event');
  }
}

// Translatables
// Included for use with string extractors like potx.

t('Events');
