<?php
/**
 * @file
 * Install, update and uninstall functions for the DruTACT Development feature.
 */

/**
 * Implements hook_enable().
 *
 * Default module permissions (devel).
 */
function drutact_dev_enable() {
  // Default module permissions (devel, schema).
  _drutact_default_module_permissions(array(
    DRUPAL_ANONYMOUS_RID => array(),
    DRUPAL_AUTHENTICATED_RID => array(),
    DRUTACT_EDITOR_RID => array(),
    DRUTACT_ADMINISTRATOR_RID => array(
      // Devel
      'access devel information',
      'execute php code',
      'switch users',
      // Schema
      'administer schema',
    ),
  ));
}

/**
 * Implements hook_disable().
 *
 * Uninstall development modules.
 * Delete development variables.
 */
function drutact_dev_disable() {
  // Uninstall development modules.
  drupal_uninstall_modules(array('devel', 'drutact_dev', 'search_krumo', 'l10n_client', 'potx', 'schema'));

  // Delete development variables.
  $variables = array(
    'admin_menu_display',
    'admin_menu_show_all',
    'dev_timer',
    'devel_api_url',
    'devel_error_handlers',
    'devel_execution',
    'devel_krumo_skin',
    'devel_memory',
    'devel_page_alter',
    'devel_query_display',
    'devel_query_sort',
    'devel_raw_names',
    'devel_rebuild_theme_registry',
    'devel_redirect_page',
    'devel_use_uncompressed_jquery',
    'devel_xhprof_directory',
    'devel_xhprof_enabled',
    'devel_xhprof_url',
    'l10n_client_disabled_paths',
    'l10n_client_server',
    '10n_client_use_server',
    'schema_database_connection',
    'schema_status_report',
    'schema_suppress_type_warnings',
  );
  foreach ($variables as $variable) {
    variable_del($variable);
  }
}
