<?php
/**
 * @file
 * Code for the DruTACT - User import feature.
 */

include_once 'drutact_user_import.features.inc';

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * Default action links (Import users).
 */
function drutact_user_import_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  switch ($root_path) {
    case 'admin/people':
      // 'Import users' action link.
      $item = menu_get_item('import/import_users_csv');
      $item['title'] = t('Import users');
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
      break;
  }
}

/**
 * Implements hook_post_features_rebuild().
 *
 * Default feed permissions (import_users_csv).
 */
function drutact_user_import_post_features_rebuild($component) {
  if ($component == 'feeds_tamper') {
    // Default feed permissions (import_users_csv).
    _drutact_import_default_feed_permissions('import_users_csv');
  }
}
