<?php
/**
 * @file
 * Code for the DruTACT Group feature.
 */

include_once 'drutact_group.features.inc';

function drutact_group_og_permission() {
  $items = array();

  // Add OG permission to
  $items['manage content'] = array(
    'title' => t('Manage content'),
    'description' => t('Users may access the Content tab on the group page.'),
    'default role' => array(OG_ADMINISTRATOR_ROLE),
    'restrict access' => TRUE,
  );

  $items['manage files'] = array(
    'title' => t('Manage files'),
    'description' => t('Users may access the Files tab on the group page.'),
    'default role' => array(OG_ADMINISTRATOR_ROLE),
    'restrict access' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_form_alter().
 */
function drutact_group_form_alter(&$form, &$form_state, $form_id)
{
  if (isset($form['og_group_ref'])) {
    if (!isset($form['additional_settings'])) {
      $form['additional_settings'] = array(
        '#type' => 'vertical_tabs',
        '#weight' => 99,
      );
    }
    // Move Group audience to Group access vertical tab.
    $form['group_access_tab'] = array(
      '#type' => 'fieldset',
      '#title' => t('Group access'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#tree' => TRUE,
      '#group' => 'additional_settings',
      '#weight' => 99,
      'og_group_ref' => $form['og_group_ref'],
    );
    $form['og_group_ref']['#access'] = FALSE;
    // Move Group visibility to Group access vertical tab.
    if (isset($form['group_content_access'])) {
      $form['group_access_tab']['group_content_access'] = $form['group_content_access'];
      $form['group_content_access']['#access'] = FALSE;
    }
    // Replicate og_complex_widget_after_build on og_group_ref.
    unset($form['group_access_tab']['og_group_ref'][LANGUAGE_NONE]['#theme']);
    unset($form['group_access_tab']['og_group_ref'][LANGUAGE_NONE]['add_more']);
    unset($form['group_access_tab']['og_group_ref'][LANGUAGE_NONE][0]['_weight']);
    // Add custom validation callback needed to fix form values.
    if (isset($form['#node_edit_form']) || $form_id == 'file_entity_add_upload') {
      array_unshift($form['#validate'], '_drutact_group_access_tab_form_validate');
    } else if($form_id == 'file_entity_edit') {
      array_unshift($form['actions']['submit']['#validate'], '_drutact_group_access_tab_form_validate');
    }
  }

  if (isset($form['membership_fields']['og_membership_request'])) {
    // Hide Request message from group subscription form.
    $form['membership_fields']['og_membership_request']['#access'] = FALSE;
  }
}

/**
 * Validation callback needed for group content node add/edit form.
 */
function _drutact_group_access_tab_form_validate($form, &$form_state) {
  // Copy og_group_ref value to its original location
  if (isset($form_state['values']['group_access_tab']['og_group_ref'])) {
    $form_state['values']['og_group_ref'] = $form_state['values']['group_access_tab']['og_group_ref'];
    unset($form_state['values']['group_access_tab']['og_group_ref']);
  }
  // Copy group_content_access value to its original location
  if (isset($form_state['values']['group_access_tab']['group_content_access'])) {
    $form_state['values']['group_content_access'] = $form_state['values']['group_access_tab']['group_content_access'];
    unset($form_state['values']['group_access_tab']['group_content_access']);
  }

  return $form;
}

/**
 * Implements hook_menu_alter().
 */
function drutact_group_menu_alter(&$items) {
  // Replace default OG group tab with administration_group_members view.
  $items['node/%/group']['type'] = MENU_CALLBACK;
  $items['node/%/group']['page callback'] = '_drutact_group_redirect_to_members';
  $items['group/%/%/admin/people']['page callback'] = '_drutact_group_redirect_to_members';
}

/**
 * Helper function to redirect to Administration - Group members tab.
 */
function _drutact_group_redirect_to_members($entity_type, $etid) {
  drupal_goto($entity_type . '/' . $etid . '/members');
}

/**
 * Implements hook_admin_paths().
 */
function drutact_group_admin_paths() {
  $paths = array(
    'node/*/contact' => TRUE,
    'node/*/content' => TRUE,
    'node/*/files' => TRUE,
    'node/*/members' => TRUE,
  );
  return $paths;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function drutact_group_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  switch ($root_path) {
    case 'admin/people/groups':
      // 'Add group' action link.
      $item = menu_get_item('node/add/group');
      $item['title'] = t('Add group');
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
      break;

    case 'node/%/files':
      // 'Add group file' action link.
      $item = menu_get_item('file/add');
      $gid = $router_item['page_arguments'][2];
      if ($item['access']) {
        $item['title'] = t('Add group File');
        $item['localized_options'] = array('query' => array('og_group_ref' => $gid));
        $data['actions']['output'][] = array(
          '#theme' => 'menu_local_action',
          '#link' => $item,
        );
      }
      break;

    case 'node/%/members':
      // Add group Member action link.
      $item = menu_get_item('group/node/' . $router_item['page_arguments'][2] . '/admin/people/add-user');
      if ($item['access']) {
        $item['title'] = t('Add group member');
        $data['actions']['output'][] = array(
          '#theme' => 'menu_local_action',
          '#link' => $item,
        );
      }
      // Change manager action link.
      $item = menu_get_item('group/node/' . $router_item['page_arguments'][2] . '/admin/manager');
      if ($item['access']) {
        $item['title'] = t('Change manager');
        $data['actions']['output'][] = array(
          '#theme' => 'menu_local_action',
          '#link' => $item,
        );
      }
      // Default members action link.
      $item = menu_get_item('group/node/' . $router_item['page_arguments'][2] . '/admin/default-members');
      if ($item['access']) {
        $item['title'] = t('Default members');
        $data['actions']['output'][] = array(
          '#theme' => 'menu_local_action',
          '#link' => $item,
        );
      }
      break;
  }
}

/**
 * Implements hook_post_features_rebuild().
 */
function drutact_group_post_features_rebuild($component) {
  if ($component == 'ctools') {
    // Default content type permissions.
    _drutact_default_content_type_permissions('group');
  }
  if ($component == 'field_instance') {
    // Group membership user field instance.
    $instance_info = field_info_instance('user', 'og_user_node', 'user');
    $instance_info['widget']['weight'] = 20;
    $instance_info['settings']['behaviors']['og_widget']['default']['widget_type'] = 'options_buttons';
    $instance_info['settings']['behaviors']['og_widget']['admin']['widget_type'] = 'options_buttons';
    $instance_info['display']['default']['label'] = 'inline';
    $instance_info['display']['default']['module'] = 'entityreference';
    $instance_info['display']['default']['type'] = 'entityreference_label';
    $instance_info['display']['default']['weight'] = 20;
    $instance_info['display']['default']['settings'] = array('link' => 1);
    field_update_instance($instance_info);
  }
  if ($component == 'rules_config') {
    // Enable default permissions.
    _drutact_default_module_permissions(array(
      DRUPAL_ANONYMOUS_RID => array(),
      DRUPAL_AUTHENTICATED_RID => array(),
      DRUTACT_EDITOR_RID => array(
        // Rules
        'use Rules component rules_file_assign_to_group',
        'use Rules component rules_node_assign_to_group',
        'use Rules component rules_user_subscribe_to_group',
      ),
      DRUTACT_ADMINISTRATOR_RID => array(
        // Organic group
        'administer group',
        // Rules
        'use Rules component rules_file_assign_to_group',
        'use Rules component rules_node_assign_to_group',
        'use Rules component rules_user_subscribe_to_group',
      )
    ));
  }
}
