<?php
/**
 * @file
 * Code for the DruTACT Sections feature.
 */

include_once 'drutact_sections.features.inc';

/**
 * Implements hook_form().
 *
 * Move Sections field to vertical tab.
 */
function drutact_sections_form_alter(&$form, &$form_state, $form_id) {
  // Move Sections field to vertical tab.
  if (isset($form['field_sections'])) {
    if (!isset($form['classification_tab'])) {
      $form['classification_tab'] = array(
        '#type' => 'fieldset',
        '#title' => t('Classification'),
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#tree' => TRUE,
        '#group' => 'additional_settings',
        '#weight' => -5,
      );
    }
    $form['classification_tab']['field_sections'] = $form['field_sections'];
    $form['field_sections']['#access'] = FALSE;

    // Add custom validation callback needed to fix form values.
    if (isset($form['#node_edit_form']) || $form_id == 'file_entity_add_upload') {
      array_unshift($form['#validate'], '_drutact_sections_classification_tab_form_validate');
    } else if($form_id == 'file_entity_edit') {
      array_unshift($form['actions']['submit']['#validate'], '_drutact_sections_classification_tab_form_validate');
    }
  }
}

/**
 * Validation callback needed for Classification tab in node add/edit form.
 */
function _drutact_sections_classification_tab_form_validate($form, &$form_state) {
  // Copy field_sections value from classification_tab to its original location
  if (isset($form_state['values']['classification_tab']['field_sections'])) {
    $form_state['values']['field_sections'] = $form_state['values']['classification_tab']['field_sections'];
    unset($form_state['values']['classification_tab']['field_sections']);
  }

  return $form;
}

/**
 * Implements hook_post_features_rebuild().
 *
 * Default vocabulary permissions (sections).
 */
function drutact_sections_post_features_rebuild($component) {
  if ($component == 'taxonomy') {
    // Default vocabulary permissions (sections).
    _drutact_default_vocabulary_permissions('sections');
  }
}

// Translatables
// Included for use with string extractors like potx.

t('Sections');
